# Generated by Django 2.1.2 on 2020-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_sela_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
