# Generated by Django 2.1.2 on 2020-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200617_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
