# Generated by Django 2.1.2 on 2020-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200617_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
