# Generated by Django 2.1.2 on 2020-06-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20200618_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='house',
            name='info',
        ),
        migrations.AddField(
            model_name='house',
            name='unit_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='unit_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
