# Generated by Django 2.1.2 on 2020-06-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20200619_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
