# Generated by Django 2.1.2 on 2020-06-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_carset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carset',
            old_name='set_num_1',
            new_name='set_num',
        ),
        migrations.RemoveField(
            model_name='carset',
            name='count',
        ),
        migrations.RemoveField(
            model_name='carset',
            name='set_num_2',
        ),
    ]
