# Generated by Django 2.1.2 on 2020-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20200620_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='carset',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carset',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carset',
            name='status',
            field=models.IntegerField(choices=[(0, '可售车位'), (1, '销控车位'), (2, '签约车位'), (3, '全款到账')], default=0),
        ),
    ]
