# Generated by Django 2.1.2 on 2020-06-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20200622_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_car',
            field=models.BooleanField(default=False),
        ),
    ]
