# Generated by Django 2.1.2 on 2020-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_house_is_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='build_num',
        ),
        migrations.AddField(
            model_name='buildnum',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.Community'),
        ),
    ]
