# Generated by Django 2.1.2 on 2020-06-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20200622_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildnum',
            name='is_car',
        ),
    ]
