# Generated by Django 2.1.2 on 2020-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_auto_20200622_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildnum',
            name='code',
        ),
        migrations.AlterField(
            model_name='buildnum',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
