# Generated by Django 2.1.2 on 2020-06-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_auto_20200624_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='car_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
